config/routes.rb
Anzahpe13Com::Application.routes.draw do
  match 'sitemap.xml' => 'sitemaps#sitemap'

  get "main/sponsors"

  get "main/register"

  get "main/host"

  get "main/contact"

  get "main/program"

  get "main/index"
  root :to => "main#index"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" />
  <title>ANZAHPE 2013 Conference</title>
  <meta name="description" content="Australian and New Zealand Association of Health Professional Educators Annual Conference in Melbourne from Monday the 24th to Thursday the 27th of June 2013.">
  <meta name="keywords" content="anzahpe, australia, australian, new zealand, health, education, professional development">
  <%= stylesheet_link_tag :application %>
  <%= javascript_include_tag :application %>
  <%= csrf_meta_tag %>
  <link rel="icon" href="assets/favicon.ico" type="image/x-icon" />
  <link rel="icon" href="assets/favicon.ico" type="image/x-icon" />
  <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700,600' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=1040" />
  <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36579772-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
</head>
<a href='#' id='gotop'>Scroll to Top</a>
<body>
  <div id="nav">
    <%= link_to main_program_path, :id => 'program', :class => current_page?(main_program_path) ? 'current' : '' do %>
      <h2>Program</h2>
    <% end %>
    <%= link_to main_sponsors_path, :id => 'sponsors', :class => current_page?(main_sponsors_path) ? 'current' : '' do %>
      <h2>Sponsors</h2>
    <% end %>
    <%= link_to main_register_path, :id => 'register', :class => current_page?(main_register_path) ? 'current' : '' do %>
      <h2>Register</h2>
    <% end %>
    <%= link_to main_host_path, :id => 'host', :class => current_page?(main_host_path) ? 'current' : '' do %>
      <h2>Host</h2>
    <% end %>
    <%= link_to main_contact_path, :id => 'contact', :class => current_page?(main_contact_path) ? 'current' : '' do %>
      <h2>Contact</h2>
    <% end %>
  </div>
  <div id="header">
    <%= link_to(main_index_path, :class => '') do %>
      <%= image_tag("ANZAHPE-2013-logo.png", :size => "330x246 ", :alt => "ANZAHPE Logo", :id => 'logo') %>
    <% end %>
  </div>
  <div id="content">

    <%= yield %>

  </div>
</body>
</html>

app/views/main/contact.html.erb
<h1>Contact</h1>
<h2>Organising Committee</h2>
<p><strong>Geoff McColl (Convenor)</strong></p>
<p>Brendan Crotty<br>
Elizabeth (Liz) Molloy<br>
Jenny Barrett<br>
Debra Nestel<br>
Margaret Bearman<br>
Karen Nightingale</p>
<h2>Conference Management</h2>
<p><strong>Antoinette Woods</strong><br>
Conference Manager</p>
<%= image_tag("taylored-statements-logo.png", :size => "205x100 ", :alt => "Taylored Statements Logo") %>
<p>PO Box 298 Hyde Park<br>
Queensland 4812<br>
T: +61 (7) 4725 5019<br>
E: <%= mail_to "info@tailoredstatements.com.au" %></p>

app/views/main/host.html.erb
<h1>Host City</h1>
<h2>Melbourne</h2>
<p>Melbourne is a creative, exciting, ever-changing city with extraordinary surprises to be discovered in every basement, rooftop and laneway. You just have to be curious enough to venture off the beaten path. The possibilities are endless, so forget what you think you know. Take a chance, roll the dice and see where it leads you.</p>
<p>Venture into Melbourne's basements, rooftops and laneways and discover gourmet feasts and fine wines, dynamic events, secret bars, boutiques and more.</p>
<%= image_tag("melbourne-images.jpg", :size => "547x401 ", :alt => "Images of Melbourne") %>
<h3>Pre & Post Touring Options</h3>
<p>Voted many times over as one of the world?s most liveable cities, Melbourne (the capital of the State of Victoria) is celebrated for its friendly locals, efficient services, fine wine and dining, and world-class facilities.</p>
<p>Few places can match the vast natural diversity on offer in Victoria.</p>
<p>From surfing the world-famous Bells Beach surf coast, to skiing at Mt Buller, from enjoying an Aussie barbecue at Emu Bottom homestead, to learning to make wine on the Mornington Peninsula , Victoria offers unique experiences which capture the imagination.
Natural wonders abound, such as the Great Ocean Road, which offers breathtaking sea views and a welcome change of pace. The majestic Murray River , with its awe-inspiring sunsets, stretches along the top of the state, while The Grampians region offers ancient and expansive landscapes.</p>
<p>For a splash of indulgence, board a luxury charter and discover Port Phillip Bay in Style. Swim with dolphins and seals, snorkel, or simply soak up the sun out on the deck. Visit Domaine Chandon, one of the Yarra Valley's stunning vineyards, for world celebrated sparkling wine, and gourmet platters filled with fresh, local produce.</p>
<p>Wind down with a treatment at an award-winning Daylesford Day Spa, or by teeing off at one of Australia?s top 10 golf courses, such as the Shearwater Cape Schanck Resort, surrounded by spectacular ocean views and magnificent natural landscapes.</p>
<p>Whether discovering Australia?s gold-mining history at an historical township such as Ballarat, or getting up close and personal with wildlife and penguins at Phillip Island Nature Parks, visit regional Victoria for an unforgettable experience of Australia.</p>
<p>For further information on Melbourne and it's transportation, touring information and accommodation visit the below links:</p>
<ul>
  <li><%= link_to "Tourism Melbourne", "http://www.visitmelbourne.com", :target => '_blank' %></li>
  <li><%= link_to "City of Melbourne", "http://www.melbourne.vic.gov.au/", :target => '_blank' %></li>
  <li><%= link_to "Melbourne Online", "http://www.melbourne.com.au", :target => '_blank' %></li>
  <li><%= link_to "Visit Victoria", "http://www.visitvictoria.com.au", :target => '_blank' %></li>
</ul>
<p>The <%= link_to "Melbourne Visitor Centre", "http://www.thatsmelbourne.com.au", :target => '_blank' %> is also conveniently situated on the corner of Swanston and Flinders Streets directly across from Flinders Street Station. Staff provide information and advice on what to see and do in Melbourne and across Victoria.</p>
<p>T: +61 3 9658 9658<br>E: <%= mail_to "tourism@melbourne.vic.gov.au" %></p>
<h3>Top 20 Things to Do in Melbourne</h3>
<ol>
  <li>Stroll, skate or soak up the sun on the St Kilda beach promenade</li>
  <li>Discover Australia's Aboriginal culture on a Koorie Heritage Walk</li>
  <li>Dine in the Colonial Tramcar Restaurant, travelling city streets while you enjoy local cuisine</li>
  <li>Meet multicultural Melbourne at the Queen Victoria Market</li>
  <li>See the city from ?The Edge?, 88 stories up in the Eureka Tower</li>
  <li>Capture the city spirit at Federation Square, home to galleries, caf&eacute;s, bars and live entertainment</li>
  <li>Eat, drink and live like a local in Melbourne's sophisticated secret laneways</li>
  <li>Swim with sea horses around the piers of the Mornington Peninsula</li>
  <li>Capture culture at the National Gallery of Victoria, with art spanning the globe</li>
  <li>Meet native and exotic animals or picnic over jazz at the Melbourne Zoo</li>
  <li>Discover the Melbourne Story at the Melbourne Museum</li>
  <li>Tee off at one of 15 championship golf courses around Melbourne</li>
  <li>Take time out at one of Melbourne's seaside day spas</li>
  <li>Experience caf&eacute; culture on Lygon Street - Melbourne's 'Little Italy'</li>
  <li>See a show at a world-class theatre as Broadway comes to Melbourne</li>
  <li>Live the sporting passion at the Melbourne Cricket Ground and National Sports Museum</li>
  <li>Drive a lap around Albert Park Lake, home to the Australian Formula 1? Grand Prix</li>
  <li>Shop at Melbourne's largest department stores, Myer and David Jones</li>
  <li>Enjoy spectacular water views and stylish restaurants in Docklands</li>
  <li>Join in the festivities at one of Melbourne's many free festivals or public events.</li>
</ol>
<h3>Self-Guided Walks</h3>
<p>Whether you're a local or a visitor, you can see the city with fresh eyes thanks to a range of free self-guided walks brochures. The walks guide you around different localities, including the banks of the Yarra River, the city's arcades and laneways, Melbourne's parks and gardens, and the historic buildings of East Melbourne. The brochures include maps and are available from the Melbourne Visitor Centre or you can obtain them on Melbourne walks.</p>
<%= image_tag("melbourne-images-2.jpg", :size => "547x401 ", :alt => "Images of Melbourne") %>
<h2>Transport</h2>
<h3>Airport Transfers</h3>
<p>The Melbourne Airport is located 20 kilometres to the CBD of Melbourne. Taxis, bus shuttles and car rental are all available from the Airport to the city and hotels.</p>
<h4>Shuttle Bus</h4>
SkyBus offers an express bus service from the airport to the city centre. This service operates 24/7, including all public holidays. Buses run from every 10 minutes throughout the day.
<ul>
  <li>$17 Adult - return $28</li>
  <li>$38 Family 2 (2 adults and 1-4 children) - return $65</li>
  <li>$24 Family 1 (1 adult and 1-4 children) - return $40</li>
  <li>$6.50 Child (4-14 years) - one way</li>
</ul>
Tickets can be purchased on arrival at the bus stop or purchased online at <%= link_to "skybus.com.au", "http://www.skybus.com.au", :target => '_blank' %>.
<p>On arrival at Southern Cross Station in the city, SkyBus provides a complimentary hotel transfer service, subject to availability.</p>
<h3>Car Rental</h3>
<p class="float"><strong><%= link_to "Avis", "http://www.avis.com.au", :target => '_blank' %></strong><br>
  13 63 33</p>
<p class="float"><strong><%= link_to "Budget", "http://www.budget.com.au", :target => '_blank' %></strong><br>
  13 27 27</p>
<p class="float"><strong><%= link_to "Europcar", "http://www.europcar.com.au", :target => '_blank' %></strong><br>
  13 13 90</p>
<p class="float"><strong><%= link_to "Hertz", "http://www.hertz.com.au", :target => '_blank' %></strong><br>
  1300 132 105</p>
<p class="float"><strong><%= link_to "Thrifty", "http://www.thrifty.com.au", :target => '_blank' %></strong><br>
  1300 367 227</p>
<h2>Venue</h2>
<h3>The Sebel & Citigate, Albert Park</h3>
<p>The Conference will be held at the Sebel & Citigate Albert in Melbourne Victoria.</p>
<p>65 Queens Road, Melbourne<br>
Victoria  3004, Australia<br>
T: +61 (3) 8554 2809<br>
W: <%= link_to "mirvachotels.com/citigate-albert-park-melbourne", "http://www.mirvachotels.com/citigate-albert-park-melbourne", :target => '_blank' %></p>
<p>Citigate Albert Park Melbourne is centrally located on Queens Road, minutes from Melbourne's central business district and St Kilda Road.</p>
<p>The accommodation rooms provide a sense of space and comfort, with many rooms overlooking stunning Albert Park Lake or the sunsets over Port Phillip Bay.</p>
<p>The hotel also features Windows Restaurant, Atrium Bar & Lounge, Cafe @ Sebel and also offers a Health Centre with a fully-equipped gymnasium, indoor heated pool, spa and sauna.</p>
<h2>General Information</h2>
<h4>Child Care</h4>
<p>Please note that no official arrangements have been made for child care during the Conference. We suggest you check with your accommodation provider who may be able to assist you further with babysitting services during your stay.</p>
<h4>Communication</h4>
<p>All communication with delegates will be by email, fax or post. If you register and do not receive confirmation within five (5) working days please contact the Conference Management Office.</p>
<h4>Climate</h4>
<p>Melbourne enjoys a temperate climate with a cool winter. Average minimum temperatures in the winter months of June through to August are 6-7 degrees.</p>
<h4>Clothing</h4>
<p>Smart casual dress applies for the conference.  Don?t forget to pack your winter woollies!</p>
<h4>Indemnity</h4>
<p>In the event of industrial disruption or other unforeseen circumstances, the Host, Organising Committee and Tailored Statements accept no responsibility for loss of monies incurred by delay or cancellation.</p>
<h4>Insurance</h4>
<p>Registration fees do not include insurance of any kind. It is strongly recommended that all delegates take out their own travel and medical insurance prior to coming to the Conference. The policy should include loss of fees / deposit through cancellation of your participation in the Conference, or through cancellation of the conference itself, loss of airfares for any reason, medical expenses, loss or damage to personal property, additional expenses and repatriation should travel arrangements have to be altered. Neither the Conference Secretariat nor the Organising Committee will take any responsibility for any participant failing to insure. Please speak to your travel agent or airline in regard to this matter.</p>
<h4>Meals & Special Dietary Requirements</h4>
<p>A variety of refreshment breaks and social functions will occur throughout the Conference. We recognise that some delegates may have special dietary requirements. Please advise the Conference Management Office via the registration form or in writing should you require alternative arrangements be made on your behalf.</p>
<h4>Messages</h4>
<p>Messages for delegates attending the conference will be placed on a message board at the conference registration desk. Please check these boards during your session breaks throughout the day.</p>
<h4>Photography</h4>
<p>During the conference and social functions there may be a photographer and/or videographer present to record the events. After the event, images may be posted on the conference website or used in future promotional materials. Please indicate you have read and understood this statement on the registration form when you register.</p>
<h4>Privacy</h4>
<p>In registering for the Conference, relevant details may be forwarded to the Organising Committee, Members and Sponsors. It is also intended to provide a delegate list for networking benefits. If you do not wish your details to be forwarded, please indicate so by ticking the relevant box on the registration form when you register.</p>
<h4>Smoking Policy</h4>
<p>The Victorian Government imposes a strict no smoking policy in venues, restaurants, bars and shopping centres.</p>

app/views/main/index.html.erb
<h1 id="title">ANZAHPE 2013</h1>
<h2 class="dates">24 - 27 JUNE 2013</h2>
<h2 class="location">The Sebel, Albert Park - Melbourne</h2>
<%= image_tag("melbourne-skyline.jpg", :size => "600x200 ", :alt => "Melbourne Skyline") %>
<h2>welcome</h2>
<p>On behalf of the Organising Committee I invite you to attend the Australian and New Zealand Association of Health Professional Educators Annual Conference in Melbourne from Monday the 24<sup>th</sup> to Thursday the 27<sup>th</sup> of June 2013.  The theme of this year's conference is the Professional Development of Health Professional Educators. If we are to develop a competent and sustainable health workforce fit for our current and future health care needs it is critical that our response is underpinned by the development of a competent and sustainable educator workforce. The ANZAHPE 2013 conference will focus on the professional development of our teachers and examine effective approaches in health professional education including simulation, clinical supervision, peer learning, inter-professional learning, assessment and education research skills.  With the assistance of an outstanding international and local conference faculty the conference will offer a variety of stimulating activities for those involved in health professional education.</p>
<p>We look forward to welcoming you to Melbourne and ANZAHPE 13.</p>
<p>- Geoff McColl</p>
<h2>Organising Committee</h2>
<p><strong>Geoff McColl (Convenor)</strong></p>
<p>Brendan Crotty<br>
Elizabeth (Liz) Molloy<br>
Jenny Barrett<br>
Debra Nestel<br>
Margaret Bearman<br>
Karen Nightingale</p>
<h2>Who Should Attend?</h2>
<p>ANZAHPE is the focal point for educators in the health professions in the Western Pacific Region and aims to promote, support and advance education in the health professions. Therefore attendance by the following groups of people is anticipated:</p>
<ul>
  <li>Academic staff teaching in allied health programs</li>
  <li>Clinicians teaching in allied health programs</li>
  <li>Undergraduate students or postgraduate students</li>
  <li>Researchers interested in health professional education</li>
  <li>Those interested in assessment, evaluation or curriculum design</li>
</ul>
<h2>Key Dates</h2>
<dl>
  <dt>Abstracts submissions</dt>
  <dd>NOW OPEN</dd>
  <dt>Deadline for abstract submission</dt>
  <dd>Close of business 7 February 2013</dd>
  <dt>Registration open</dt>
  <dd>December 2012</dd>
  <dt>Acceptance emailed</dt>
  <dd>7 March 2013</dd>
  <dt>Presenter / early bird registration close</dt>
  <dd>8 April 2013</dd>
  <dt>Provisional Program available</dt>
  <dd>15 April 2013</dd>
</dl>

app/views/main/register.html.erb
<h1>Registration</h1>
<p class="notify">ANZAHPE invite delegates to register online.</p>
<p>On receipt of your confirmation letter it is advisable to check all items listed. Any changes or alternations must be made in writing to the Conference Management Office. Please note that registration fees does not include your travel to Melbourne, accommodation, pre & post touring, accompanying person?s activities and any expenses charged to the hotel room.</p>
<%= link_to "Download Registration Brochure v1", "/assets/ANZAHPE13-Registration-Brochure-v1.pdf", :class => 'document', :target => '_blank' %>
<table width="100%" class="striped">
  <tr valign="top">
    <caption>all prices are inclusive of GST.</caption>
    <th><br></th>
    <th>Early Bird <br><span class="cavet">(prior to 8 April)</span></th>
    <th>Standard</th>
  </tr>
  <tr>
    <td>Full Member Registration</td>
    <td align="center">$750</td>
    <td align="center">$850</td>
  </tr>
  <tr>
    <td>Non Member Registration</td>
    <td align="center">$950</td>
    <td align="center">$1050</td>
  </tr>
  <tr>
    <td>Member Day Registration</td>
    <td align="center">$360</td>
    <td align="center">$360</td>
  </tr>
  <tr>
    <td>Non Member Day Registration</td>
    <td align="center">$390</td>
    <td align="center">$390</td>
  </tr>
  <tr>
    <td>Student Full Registration</td>
    <td align="center">$325</td>
    <td align="center">$325</td>
  </tr>
  <tr>
    <td>Student Day Registration</td>
    <td align="center">$165</td>
    <td align="center">$165</td>
  </tr>
</table>
<h2>Entitlements</h2>
<table width="100%" class="striped">
  <tr valign="top">
    <th>Inclusions</th>
    <th width="17%">Full Delegates</th>
    <th width="17%">Day Delegate</th>
  </tr>
  <tr>
    <td>Conference Satchel</td>
    <td align="center">x</td>
    <td align="center">x</td>
  </tr>
  <tr>
    <td>Name Badge</td>
    <td align="center">x</td>
    <td align="center">x</td>
  </tr>
  <tr>
    <td>All Conference Publications</td>
    <td align="center">x</td>
    <td align="center">x</td>
  </tr>
  <tr>
    <td>Morning, Afternoon Tea Breaks and Lunches as per the Program</td>
    <td align="center">x</td>
    <td align="center">x<br><span class="cavet">(on registered day only)</span></td>
  </tr>
  <tr>
    <td>Welcome Reception</td>
    <td align="center">x</td>
    <td align="center"></td>
  </tr>
  <tr>
    <td>Conference Dinner</td>
    <td align="center">x</td>
    <td align="center"></td>
  </tr>
</table>
<h2>Pre-Conference Workshops</h2>
<table width="100%" class="striped">
  <caption>all prices are inclusive of GST.</caption>
  <tr>
    <th>Workshop</th>
    <th width="17%">Cost</th>
  </tr>
  <tr>
    <td>Workshop #1: Building Healthcare Education Research Capacity: a Workshop for Education Researchers, Practitioners, and Leaders</td>
    <td align="center">$88</td>
  </tr>
  <tr>
    <td>Workshop #2: Learners in Difficulty - a Faculty Development Priority - Introduces Key Themes, Develops a Diagnostic and Management Framework</td>
    <td align="center">$88</td>
  </tr>
  <tr>
    <td>Workshop #3: Rethinking Feedback</td>
    <td align="center">$88</td>
  </tr>
  <tr>
    <td>Workshop #4: Measuring Assessment Quality and Stability using the Rasch Model</td>
    <td align="center">$88</td>
  </tr>
  <tr>
  	<td>Workshop #5: Teaching on the Run: Facilitating Inter professional Education in the Clinical Setting</td>
  	<td align="center">$88</td>
  </tr>
  <tr>
  	<td>Workshop #6: Theories that Inform Educational Practice</td>
  	<td align="center">$88</td>
  </tr>
</table>
<h2>Additional Social Function Tickets</h2>
<p>Social Function tickets may be purchased for delegate guests to attend various functions.</p>
<table width="100%" class="striped">
  <caption>all prices are inclusive of GST.</caption>
  <tr>
    <th>Function</th>
    <th>Date</th>
    <th width="17%">Cost</th>
  </tr>
  <tr>
    <td>Welcome Reception</td>
    <td>Monday 24 June</td>
    <td align="center">$66</td>
  </tr>
  <tr>
    <td>Conference Dinner</td>
    <td>Wednesday 26 June</td>
    <td align="center">$110</td>
  </tr>
</table>
<h2>Social Program</h2>
<h3>Welcome Reception</h3>
<h4>Monday 24 June, Alice The Sebel, Albert Park</h4>
<p>The welcome reception is a great opportunity to catch up with colleagues and old friends and also a wonderful opportunity to make new ones. The night will be designed for networking, meet and greet and a lovely relaxing way to start the conference.</p>
<p>Cost for this function is included in the full registration fee. Intention to attend this function must be indicated on the registration form.</p>
<p>Additional tickets can be purchased via the registration form.</p>
<h3>Conference Dinner</h3>
<h4>Wednesday 26 June, The Sebel, Albert Park</h4>
<p>The Conference Dinner will be held at The Sebel, Albert Park. A networking opportunity for delegates, the conference dinner will provide a 3 course meal with beer, wine and soft-drinks. The dinner will also include award presentations and entertainment.</p>
<p>Cost for this function is included in the full registration fee. Intention to attend this function must be indicated on the registration form.</p>
<p>Additional tickets can be purchased via the registration form.</p>
<h2>Accommodation</h2>
<p>Delegates can take advantage of in-house and local accommodation at special rates. We encourage delegates to book accommodation well in advance as there are strict release dates and a high demand for accommodation in the city especially during this period due to the Rugby World Cup.</p>
<h3>Rooms</h3>
<p>The following rooms are available:</p>
<ul>
  <li>The Citigate Guest Room - $170 per night (room only)</li>
  <li>The Sebel Guest Room - $180 per night (room only)</li>
</ul>
<p>Both rooms are available in either a single, twin or double and can be made to include a hot buffet breakfast with an additional fee.</p>
<ul>
  <li>"Double" refers to a room with a one double bed.</li>
  <li>"Twin" refers to a room with two beds.</li>
  <li>"Single" refers to a room with single occupancy.</li>
</ul>
<h3>Payment of Accommodation</h3>
<p>Accommodation accounts are to be settled by the individual direct with the hotel/property. The Conference will ONLY accept credit card details for accommodation as a method of securing the room. The credit card details are passed on to the hotel as security for your room and the first night of accommodation may be applied to guarantee your booking. This will be done by the hotel. All accommodation rates are quoted in AUD dollars. Accommodation is charged on a per room basis, not per person.</p>
<p>Please specify your room type on the online booking form where indicated. Accommodation rates are for room only and do not include breakfast.</p>
<h3>Deadlines</h3>
<p>The hotels impose strict cut off dates for bookings. All hotel rooms will be released by Tailored Statements by 23 May 2013. For accommodation bookings after this time, will be on request only and will be subject to availability.</p>
<h3>Cancellation Policy</h3>
<p>Any changes to your original booking information must be forwarded in writing to the Conference Management Office via email <%= mail_to 'info@tailoredstatements.com.au' %></p>
<h2>Payment</h2>
<ul>
  <li>Registrations will be accepted online via the Conference website - anzahpe13.com</li>
  <li>All amounts are in Australian Dollars. Overseas registrants should arrange payment via credit card.</li>
  <li>Registration fees may be paid by MasterCard and Visa. Diners and AMEX are not accepted.</li>
  <li>Delegates will receive a confirmation email or letter which will include a tax invoice.</li>
</ul>
<h3>Good and Services Tax</h3>
<p>A Tax invoice will be issued upon registration and this can be given to the Accounts Department for GST records. On processing the registration form, the Tax Invoice will be in the name of the delegate unless otherwise requested. Reprints for Tax invoices will be subject to a $25 Administration fee.</p>
<h3>Cancellation Policy</h3>
<p>All cancellations of attendance must be made in writing to the <%= link_to 'Conference Management Office', main_contact_path %>.</p>
<ul>
  <li>A full refund, less a cancellation fee of $150 will be made on those received before 8 April 2013.</li>
  <li>No refund will be made after 8 April 2013.</li>
  <li>All refunds will be paid after the conclusion of the Conference.</li>
</ul>
<%= link_to 'Click for Full Registration', 'https://www.conferenceonline.com/index.cfm?page=booking&object=conference&id=17329&categorykey=59422A4E%2DFA89%2D467F%2D9C12%2DD9951F06CAE8&clear=1', :class => 'button', :target => '_blank' %>
<%= link_to 'Click for Day Registration', 'https://www.conferenceonline.com/index.cfm?page=booking&object=conference&id=17329&categorykey=19281311%2D4711%2D46CA%2DAB92%2D3221F56E7422&clear=1', :class => 'button', :target => '_blank' %>

app/views/main/sponsors.html.erb
<h1>Sponsors</h1>
<h2>Sponsorship & Exhibition Opportunities</h2>
<p>The sponsorship of the ANZAHPE Conference provides a unique opportunity for your organisation. Sponsorship and exhibition opportunities are now open. For further information please contact the <%= link_to "Conference Management Office", main_contact_path %>.</p>
<%= link_to "Download the sponsorship and exhibition prospectus", "/assets/ANZAHPE13-Sponsorship&Exhibition-Packages.pdf", :class => 'document', :target => '_blank' %>
<p>The Organising Committee would like to acknowledge the following sponsors
for their partnership in ANZAHPE 13.</p>
<%= link_to("http://www.flinders.edu.au", :target => '_blank') do %>
  <div class="sponsor flinders first">
    <h2>Platinum Sponsor</h2>
    <p>Master of Clinical Education, Flinders University</p>
  </div>
<% end %>
<%= link_to("http://www.monash.edu.au", :target => '_blank') do %>
  <div class="sponsor monash">
    <h2>Platinum Sponsor</h2>
    <p>Monash University<br>
      Gippsland Medical School,<br>
      School of Rural Health
    </p>
  </div>
<% end%>
<%= link_to("http://unimelb.edu.au", :target => '_blank') do %>
  <div class="sponsor unimelb">
    <h2>Platinum Sponsor</h2>
    <p>The University of Melbourne</p>
  </div>
<% end %>
<%= link_to("http://www.deakin.edu.au", :target => '_blank') do %>
  <div class="sponsor deakin first">
    <h2>Platinum Sponsor</h2>
    <p>Deakin University</p>
  </div>
<% end %>
<%= link_to("http://www.monash.edu.au", :target => '_blank') do %>
  <div class="sponsor monash">
    <h2>Platinum Sponsor</h2>
    <p>Monash University<br>
      HealthPEER (Health Professions Education and Educational Research)
    </p>
  </div>
<% end %>
<%= link_to("http://www.hwa.gov.au", :target => '_blank') do %>
  <div class="sponsor hwa">
    <h2>GOLD Sponsor</h2>
    <p>Health Workforce Australia</p>
  </div>
<% end %>
<%= link_to("http://www.pcc4u.org", :target => '_blank') do %>
  <div class="sponsor pcc4u first">
    <h2>Silver Sponsor</h2>
    <p>PCC4U Project</p>
  </div>
<% end %>
<%= link_to("http://www.tellcentre.org", :target => '_blank') do %>
  <div class="sponsor tell">
    <h2>Silver Sponsor</h2>
    <p>University of Western Australia/TELL Project</p>
  </div>
<% end %>

<hr>